application: technogeek-labs
version: alpha-017
runtime: go
api_version: go1

env_variables:
  DISCOURSE_WEBHOOK: ""
  DISCOURSE_API_KEY: ""
  TELEGRAM_WEBHOOK: ""
  TELEGRAM_SECRET: ""
  TELEGRAM_BOT_USERNAME: ""
  BOT_COMMAND: ""
  BOT_SUBSCRIPTION_COMMAND: ""


handlers:
- url: /
  script: _go_app

- url: /hook/(.*)
  script: _go_app

- url: /telegram/(.*)
  script: _go_app
